name: Release docs
on:
    push:
        branches: [ dev-docs ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
          sudo apt-get install pandoc
          python -m pip install --upgrade pip
          pip install jupyterlab sphinx
          pip install -e .
    - name: Build docs
      run: |
          cd docs/
          python -c "import cbmos"
          make notebooks api
          make html
